### ISSUE TITLE
"Or functionality" still active when clicking the "Recipient Organization" link.

### ISSUE THREAD

**Issue by gustavohandrade** [ajah/sks-interface#30]
When the user clicks the link to search for an organization, the search should be for that specific organization. If the "Or functionality" is active, the search will include all organizations with any of the words in the name of the referred organization.

**Comment by psdcode** [comment]
- 1.5hr
---

Issue is operator state specified in address bar is not correctly synced with the operator tracked inside the React search context. Will need to bidirectionally sync their state, then can simply use `<Link to={/*address with operator type specified */} />. 
Will also check if really necessary to track operator state in SearchContext, may simplify things if simply rely on query param as single source of truth & simply default to one of the two possible values if not provided.

I imagine resolving this issue will likely resolve a few other minor bugs I noticed related to the search bar/query
