### ISSUE TITLE
Console errors, unnecessary console logs, and compile warnings

### ISSUE THREAD

**Issue by psdcode** [ajah/sks-interface#36]
There are a several persistent console errors, console outs, and compile warnings that are preventing efficient use of of the console for development. Examples

- <img width="1117" alt="Screen Shot 2022-08-15 at 23 06 28" src="https://user-images.githubusercontent.com/10729355/184794529-d4c25191-1564-469d-9866-ad8e2f5ce9e5.png">

- <img width="1029" alt="Screen Shot 2022-08-15 at 23 06 19" src="https://user-images.githubusercontent.com/10729355/184794534-800a2f1a-bee7-4e2b-aac8-4dd5561331ff.png">

- <img width="788" alt="Screen Shot 2022-08-15 at 19 29 08" src="https://user-images.githubusercontent.com/10729355/184794619-c5b79c1f-579b-4436-b9d5-cd54d7591ed6.png">

**Comment by psdcode** [comment]
1hr

**Comment by hjweinreb** [comment]
Hi @psdcode, I just noticed the last few issues opened by Gustavo. They weren't assigned to me so I didn't get any emails about them except one where my @ was mentioned. Looking over them, they seem like relatively simple fixes. 

I also saw your comment and I was mistaken when I said a page refresh would reset the search queries. Linking to a specific search result should work as expected. 

I see that you assigned this issue to yourself and was wondering if you will be working on the code base as well.

If you have an Ajah email, I've been communicating with the rest of the team over Google chat and I'm used to getting updates on there. It might be an easier way to keep things rolling. Mine is harrison.weinreb@ajah.ca. I think it would be beneficial to discuss the direction of the project and who will be working on what.

**Comment by psdcode** [comment]
Hi @hjweinreb , thanks for your message! We were not formally introduced so I'm glad you reached out 👋
From the meeting last friday with Jesse and Gustavo, I was informed to look into fixing the four issues currently in the "in progress" column in the SKS Hub Roadmap. I did comment on each of them, but then noticed that you are assigned to https://github.com/ajah/sks-interface/issues/5, so I deleted my comment on that one until Jesse confirms whether he would prefer you to continue with it, or should I take over. (Since I tagged you in the comment at the time, you may have received an email notification for that anyway). 

With respect to linking to a search result, my impression was the filters (eg, activity and/or institution) are always reset to a default value, even if provided with specific value in the query.

With regards to this issue, it's just some cleanup I need to do on the codebase before I get started with the other issues. It's approval is pending until Gustavo discusses it with Jesse tomorrow.

Feel free to reach me on google chat at patrick dot dorosz at gmail dot com, we can touch base on there as well.
