### ISSUE TITLE
Improve user experience when using the filters in the search page

### ISSUE THREAD

**Issue by dani-ajah** [ajah/sks-interface#4]
As a user of the platform, I want to be able to select filters and have the results load automatically without me having to update the page every time I choose a new combination of filters to easily adjust my search with the results I get.

**Comment by gustavohandrade** [comment]
The filter functionality is unintuitive as is. When selecting a filter, the filtered results should show automatically. After selecting the desired filter, the user needs to click on the search button at the search bar again, which may seem to the user that the filter is not working.
