### ISSUE TITLE
"Download results" not working.

### ISSUE THREAD

**Issue by gustavohandrade** [ajah/sks-interface#48]
We have three different instances of this error:
When no filter is applied: the page reloads, but nothing happens.
When the city filter is applied: an "Internal Server Error" message displayed
It only works when one uses the province filter or clicks the search button twice.

**Comment by gustavohandrade** [comment]
The download results link is not available.

**Comment by brittwitham** [comment]
@gustavohandrade this is blocked by my backend fixes, I'm intentionally holding off merging the PR until I've made those changes so I can determine whether this fixes the behaviour for the city filter or not
