### ISSUE TITLE
Improve city filter

### ISSUE THREAD

**Issue by gustavohandrade** [ajah/sks-interface#49]
Changing city search button to a '+', and having the city name show up in a tile right below when clicking the + button. Then, as long as the tile exists, we disable the city entry field & plus button.

![Image](https://user-images.githubusercontent.com/106772124/186995067-1b0dbd2c-0ca5-4493-90d2-dbe4ef9bcca3.png)

**Comment by psdcode** [comment]
Nice, yeah this is a good solution

> Changing city search button to a '+', and having the city name show up in a tile right below when clicking the + button. Then, as long as the tile exists, we disable the city entry field & plus button.
> 
> ![Image](https://user-images.githubusercontent.com/106772124/186995067-1b0dbd2c-0ca5-4493-90d2-dbe4ef9bcca3.png)
@gustavohandrade 
Nice, yeah I think this is a good solution. Similar limit as keywords, up to 5 cities?

**Comment by gustavohandrade** [comment]
Hi @psdcode, up to 5 cities would be enough.

**Comment by psdcode** [comment]
Time spent: 2.5hrs
