### ISSUE TITLE
Province filter returns blank

### ISSUE THREAD

**Issue by gustavohandrade** [ajah/sks-interface#58]
@psdcode When a province is selected on the filter menu, it returns a blank page. Britt sent the following image related to this issue.

<img width="1398" alt="image (1)" src="https://user-images.githubusercontent.com/106772124/204858893-26608853-976f-4c36-9fea-8a1e5c71a302.png">

**Comment by psdcode** [comment]
@gustavohandrade this is because Brittany changed the frontend codes for provinces a month ago, without realizing I parse them on the frontend before sending them off to the backend. miscommunication between us. fixed now
