### ISSUE TITLE
Separate search terms by comma or a box to preserve phrases

### ISSUE THREAD

**Issue by dani-ajah** [ajah/sks-interface#6]
As a user of the platform, I want to be able to distinguish between the search terms I use, in particular when inputting a multiple-word term (eg. search "Career development" as one term instead of "Career" AND "Development")

This would entail changing how the query string is parsed so that exact phrases (e.g. "career development") are preserved instead of separated into individual words by the search engine. This goes hand-in-hand with the task to preserve search terms in the search bar after the query is launched.

**Comment by dani-ajah** [comment]
Could we make a small "?" button/hover-over icon where we give users a little more info on how to conduct their search. Include something along the lines of: "To complete your search enter a keyword or phrase and hit the enter key or click the search button. Enter one keyword at a time. Your results will update automatically as more keywords are added"

**Comment by brittwitham** [comment]
@hjweinreb restore work on "?" button and increase # of keywords from 4 to 5

**Comment by brittwitham** [comment]
Current state of the hover button: 

![Image](https://user-images.githubusercontent.com/39388116/174356506-0da5f31a-6af0-4a3b-ac6a-bf6dd7249f8b.png)
