### ISSUE TITLE
Remaining frontend issues

### ISSUE THREAD

**Issue by gustavohandrade** [ajah/sks-interface#66]
@psdcode 

Custom filter search not running automatically:

Britt made the required changes on the backend to make the custom filters work. However, the custom filter is not running automatically when there are no keywords on the search. When you get to the search page and click in one of the custom filters, the search should run automatically with keywords established in it. Britt ran some tests and queries, and the API is working.

Frontend results not always matching the download results:

I found out this issue searching for waste and then clicking the "Sustainability" custom filter. The results presented on the results page shows 11 organizations in total (which have at least one of the keywords on the web_site text field). However, the csv file still shows all results (without the filter applied). Here, once again, Britt ran some backend tests and it worked. Here is what she said: "I tested it on the live site and got the same result, so there must be a discrepancy between the request being launched by the interface and the link above (https://sks-server-ajah-ttwto.ondigitalocean.app/search?q=waste&city=&doctype=activity,entity&operator=and&region=&terms=efc_sustainability)

**Comment by psdcode** [comment]
a) @gustavohandrade I will add instant search. is there any other filters that you would like the search to happen instantly when selected? (eg city, region? I assume _not_ for doctype)

b) I will check this out, but I think data is generated by a remote endpoint?
